---
# https://qiita.com/shifumin/items/288f486a0e41439b9eb0 の手順をtask化したもの
- name: Install required packages.
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      # required build packages: https://qiita.com/tomy0610/items/66e292f80aa1adc1161d
      - gcc
      - curl-devel
      - expat-devel
      - gettext-devel
      - openssl-devel
      - zlib-devel
      - perl-ExtUtils-MakeMaker
      - autoconf
      # required unarchive
      - unzip
  become: yes

- name: Get git package.
  unarchive:
    src: "https://github.com/git/git/archive/v{{ git_version }}.zip"
    dest: "{{ dest_dir }}"
    remote_src: yes
  become: yes

- name: Create template directory.
  file:
    path: "{{ temp_dir }}"
    state: directory
  become: yes

- name: Build git to template direcotry.
  shell: |
    cd {{ dest_dir }}/git-{{ git_version }}
    make prefix={{ temp_dir }} all
    make prefix={{ temp_dir }} install
  become: yes

- name: List installed files.
  shell: "find {{ temp_dir }} -type f -print > {{ temp_dir }}/git-install-list.txt"

- name: Replace installed path.
  replace:
    path: "{{ temp_dir }}/git-install-list.txt"
    regexp: "/tmp/git_uninstall"
    replace: "/usr/local"

- name: Remove installed files.
  shell: "cat {{ temp_dir }}/git-install-list.txt | xargs rm -f"
  become: yes

- name: Remove template directory.
  file:
    path: "{{ temp_dir }}"
    state: absent

# - name: Remove dest directory.
#   file:
#     path: "{{ dest_dir }}/git-{{ git_version }}"
#     state: absent
